apiVersion: skaffold/v4beta7
kind: Config
manifests:
  rawYaml:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/cloud/deploy.yaml
  - ./infra/k8s/*
build:
  local: 
    push: false
  artifacts:
    - image: ticketing-app-auth-service
      context: auth-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ticketing-app-frontend-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .