apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: pre-requisite
profiles:
- name: dev
  manifests:
    rawYaml:
    - ./infra/k8s/pre-requisite-manifests/*
    - ./infra/k8s/pre-requisite-manifests-dev/*
- name: prod
  manifests:
    rawYaml:
    - ./infra/k8s/pre-requisite-manifests/*
    - ./infra/k8s/pre-requisite-manifests-prod/*
---
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: ticketing-app
profiles:
- name: dev
  manifests:
    rawYaml:
    - ./infra/k8s/application-manifests/*
    - ./infra/k8s/application-manifests-dev/*
  build:
    local: 
      push: false
    artifacts:
      - image: ticketing-app-auth-service
        context: auth-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: ticketing-app-frontend-client
        context: client
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: '**/*.js'
              dest: .
      - image: ticketing-app-ticket-service
        context: ticket-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: ticketing-app-order-service
        context: order-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: ticketing-app-expiration-service
        context: expiration-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: ticketing-app-payment-service
        context: payment-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
- name: prod
  manifests:
    rawYaml:
    - ./infra/k8s/application-manifests/*
    - ./infra/k8s/application-manifests-prod/*
  build:
    googleCloudBuild:
      projectId: ticketing-app-prod
    artifacts:
      - image: gcr.io/ticketing-app-prod/ticketing-app-auth-service
        context: auth-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: gcr.io/ticketing-app-prod/ticketing-app-frontend-client
        context: client
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: '**/*.js'
              dest: .
      - image: gcr.io/ticketing-app-prod/ticketing-app-ticket-service
        context: ticket-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: gcr.io/ticketing-app-prod/ticketing-app-order-service
        context: order-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: gcr.io/ticketing-app-prod/ticketing-app-expiration-service
        context: expiration-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: gcr.io/ticketing-app-prod/ticketing-app-payment-service
        context: payment-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
    