apiVersion: skaffold/v4beta7
kind: Config
metadata:
    name: ingress-nginx
manifests:
  rawYaml:
  - ./infra/k8s/ingress-nginx-controller.yaml
---
apiVersion: skaffold/v4beta7
kind: Config
metadata:
    name: ticketing-app
manifests:
  rawYaml:
  - ./infra/k8s/namespace/*
  - ./infra/k8s/client/*
  - ./infra/k8s/database/*
  - ./infra/k8s/auth-service/*
  - ./infra/k8s/ingress/*
build:
  ## Use the following section when deploying to local Kubernetes Cluster. Comment out the googleCloudBuild: projectId: ticketing-app-prod part!
  local: 
    push: false
  ## Use the following section when deploying to Google Cloud Kubernetes Cluster. Comment out the local: push: false part!
  # googleCloudBuild:
  #   projectId: ticketing-app-prod
  artifacts:
    - image: ticketing-app-auth-service
      context: auth-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ticketing-app-frontend-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .