apiVersion: skaffold/v4beta7
kind: Config
metadata:
    name: ingress-nginx
manifests:
  rawYaml:
  - ./infra/k8s/ingress-nginx-controller.yaml
---
apiVersion: skaffold/v4beta7
kind: Config
metadata:
    name: ticketing-app
manifests:
  rawYaml:
  - ./infra/k8s/01-namespace/*
  - ./infra/k8s/02-rabbitmq-service/*
  - ./infra/k8s/03-client/*
  - ./infra/k8s/04-database/*
  - ./infra/k8s/05-auth-service/*
  - ./infra/k8s/06-ticket-service/*
  - ./infra/k8s/07-order-service/*
  - ./infra/k8s/08-expiration-service/*
  - ./infra/k8s/09-payment-service/*
  - ./infra/k8s/10-ingress/*
profiles:
- name: dev
  build:
    local: 
      push: false
    artifacts:
      - image: ticketing-app-auth-service
        context: auth-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: ticketing-app-frontend-client
        context: client
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: '**/*.js'
              dest: .
      - image: ticketing-app-ticket-service
        context: ticket-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: ticketing-app-order-service
        context: order-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: ticketing-app-expiration-service
        context: expiration-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: ticketing-app-payment-service
        context: payment-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
- name: prod
  build:
    googleCloudBuild:
      projectId: ticketing-app-prod
    artifacts:
      - image: gcr.io/ticketing-app-prod/ticketing-app-auth-service
        context: auth-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: gcr.io/ticketing-app-prod/ticketing-app-frontend-client
        context: client
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: '**/*.js'
              dest: .
      - image: gcr.io/ticketing-app-prod/ticketing-app-ticket-service
        context: ticket-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: gcr.io/ticketing-app-prod/ticketing-app-order-service
        context: order-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: gcr.io/ticketing-app-prod/ticketing-app-expiration-service
        context: expiration-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: gcr.io/ticketing-app-prod/ticketing-app-payment-service
        context: payment-service
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
    