apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-deployment
  namespace: ticketing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
        - name: ticket
          image: ticketing-app-ticket-service:latest
          imagePullPolicy: Never
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-service
  namespace: ticketing-app
spec:
  type: ClusterIP
  selector:
    app: ticket
  ports:
    - name: ticket
      protocol: TCP
      port: 3000
      targetPort: 3000