apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: ticketing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          ## Use the following image name when deploying on Google Cloud Kubernetes Cluster!
          # image: us.gcr.io/ticketing-app-prod/ticketing-app-frontend-client:latest
          ## Use the following image name when deploying on local Kubernetes Cluster!
          image: ticketing-app-frontend-client:latest
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: ticketing-app
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000