---
- name: Deploy Application on GKE
  hosts: jenkins_agent_node
  gather_facts: false

  tasks:
    - name: Set the Kubernetes context 
      shell: |
        KUBECTL_GCLOUD_CONTEXT="gke_${K8S_CLUSTER_PROJ}_${K8S_CLUSTER_ZONE}_${K8S_CLUSTER_NAME}"
        kubectl config use-context ${KUBECTL_GCLOUD_CONTEXT}
      environment:
        K8S_CLUSTER_PROJ: "{{ K8S_CLUSTER_PROJ }}"
        K8S_CLUSTER_NAME: "{{ K8S_CLUSTER_NAME }}"
        K8S_CLUSTER_ZONE: "{{ K8S_CLUSTER_ZONE }}"
    
    # - name: Load Kubernetes Configuration
      # k8s_config:
      #   context: KUBECTL_GCLOUD_CONTEXT

    - name: Authenticate with Google Cloud 
      command: gcloud auth activate-service-account --key-file=${GCLOUD_KEY}
      environment:
        GCLOUD_KEY: "{{ GCLOUD_KEY }}"

    - name: Configure kubectl
      command: gcloud container clusters get-credentials your-cluster-name --zone your-cluster-zone --project your-gcp-project

    - name: Deploy Ingress Controller via Skaffold
      command: skaffold deploy --profile prod --module {{ MODULE_NAMESPACE_1 }}
      environment:
        MODULE_NAMESPACE_1: "{{ MODULE_NAMESPACE_1 }}"
      register: skaffold_result

    - name: Debug Skaffold Output
      debug:
        var: skaffold_result

    # - name: Wait for Skaffold Deployment Completion
    #   wait_for:
    #     timeout: 120
    #     path: "{{ ansible_env.HOME }}/.kube/config"

    - name: Create Application Namespace
      command: kubectl apply -f ./infra/k8s/namespace/*

    - name: Create JWT Secret
      command: kubectl create secret generic jwt-secret -n {{ MODULE_NAMESPACE_2 }} --from-literal=JWT_KEY="{{ JWT_KEY }}"
      environment:
        MODULE_NAMESPACE_2: "{{ MODULE_NAMESPACE_2 }}"
        JWT_KEY: "{{ JWT_KEY }}"

    - name: Deploy Updated Kubernetes Manifests
      command: kubectl apply -f ./infra/k8s/client/* ./infra/k8s/database/* ./infra/k8s/auth-service/* ./infra/k8s/ingress/*