apiVersion: v1
kind: Secret
metadata:
  name: user-credentials-secret
  namespace: ticketing-app
type: Opaque
stringData:
  username: example
  password: whyareyoulookinghere
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbitmq-user
  namespace: ticketing-app
spec:
  tags:
  - administrator
  rabbitmqClusterReference:
    name: rabbitmq-cluster 
  importCredentialsSecret:
    name: user-credentials-secret