apiVersion: v1
kind: Secret
metadata:
  name: user-credentials-secret
  namespace: ticketing-app
type: Opaque
stringData:
  username: example
  password: whyareyoulookinghere
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbitmq-user
  namespace: ticketing-app
spec:
  tags:
  - administrator
  rabbitmqClusterReference:
    name: rabbitmq-cluster 
  importCredentialsSecret:
    name: user-credentials-secret
---
apiVersion: rabbitmq.com/v1beta1
kind: TopicPermission
metadata:
  name: rabbitmq-user-permission
  namespace: ticketing-app
spec:
  vhost: "/" # name of a vhost; required
  user: "rabbitmq-user" # name of RabbitMQ user
  permissions:
    exchange: rabbitmq-exchange
    write: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq-cluster