apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: payment-service-queue-binding
  namespace: ticketing-app
spec:
  source: ticketing-app-exchange        # an existing exchange
  destination: payment-service-queue    # an existing queue
  destinationType: queue                # can be 'queue' or 'exchange'
  routingKey: "order.#"
  rabbitmqClusterReference:
    name: rabbitmq-cluster